import type { Course } from 'src/types/course';

export const mockCourses: Course[] = [
  {
    id: '1',
    name: 'Full Stack Web Development',
    code: 'WEB-101',
    description: 'Learn to build complete web applications from frontend to backend using modern technologies.',
    category: 'Web Development',
    level: 'beginner',
    price: 299,
    instructor: 'John Smith',
    instructorId: 'instr_1',
    duration: 40,
    students: 234,
    rating: 4.9,
    status: 'active',
    image: '/assets/images/courses/web-dev.jpg',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Machine Learning Fundamentals',
    code: 'ML-101',
    description: 'Introduction to machine learning concepts, algorithms, and practical applications using Python.',
    category: 'Data Science',
    level: 'intermediate',
    price: 399,
    instructor: 'Dr. Lisa Wang',
    instructorId: 'instr_2',
    duration: 50,
    students: 189,
    rating: 4.7,
    status: 'active',
    image: '/assets/images/courses/ml.jpg',
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '3',
    name: 'Mobile App Development with React Native',
    code: 'MOBILE-101',
    description: 'Build cross-platform mobile applications using React Native and JavaScript.',
    category: 'Mobile Development',
    level: 'intermediate',
    price: 349,
    instructor: 'Alex Johnson',
    instructorId: 'instr_3',
    duration: 45,
    students: 156,
    rating: 4.8,
    status: 'active',
    image: '/assets/images/courses/mobile.jpg',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '4',
    name: 'Advanced TypeScript',
    code: 'TS-201',
    description: 'Master advanced TypeScript concepts including generics, decorators, and type utilities.',
    category: 'Programming',
    level: 'advanced',
    price: 279,
    instructor: 'Sarah Chen',
    instructorId: 'instr_4',
    duration: 35,
    students: 98,
    rating: 4.9,
    status: 'active',
    image: '/assets/images/courses/typescript.jpg',
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '5',
    name: 'Cloud Architecture with AWS',
    code: 'AWS-101',
    description: 'Learn to design and deploy scalable cloud applications on Amazon Web Services.',
    category: 'Cloud Computing',
    level: 'intermediate',
    price: 449,
    instructor: 'Michael Brown',
    instructorId: 'instr_5',
    duration: 55,
    students: 142,
    rating: 4.6,
    status: 'active',
    image: '/assets/images/courses/aws.jpg',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '6',
    name: 'UI/UX Design Principles',
    code: 'DESIGN-101',
    description: 'Create beautiful and user-friendly interfaces with modern design principles and tools.',
    category: 'Design',
    level: 'beginner',
    price: 199,
    instructor: 'Emma Davis',
    instructorId: 'instr_6',
    duration: 30,
    students: 267,
    rating: 4.7,
    status: 'active',
    image: '/assets/images/courses/design.jpg',
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-20'),
  },
];
